### ISSUE TITLE
Merhaba

### ISSUE THREAD

**Issue by vehbi54** [ahmetozalp/kurumsal-danismanlik-php#1]
Hocam öncelikle böyle güzel scripti ücretsiz verdiğiniz için teşekkür ederim size ufak bir sorum olacaktı 
admin/tasarla 
user ve şifreyi değiştirmeyi denememe rağmen yapamadım bu konuda yardımcı olurmusunuz

**Comment by ahmetozalp** [comment]
phpmyadmin e girin iwt_users tablosundan password olan kısma https://wmaraci.com/md5-sha1-sifre-olusturucu burdan md5 oluşturup degiştiriniz.
