### ISSUE TITLE
Anasayfaya yönlenme sorunu

### ISSUE THREAD

**Issue by hakantopuzoglu** [ahmetozalp/kurumsal-danismanlik-php#2]
config.php ayarlarını yaptımama doğrudan skonseptdanismanlik.com adresine yönleniyor. 
Yapmamız gereken başka işlem var mı? 

Saygılarımla,

**Comment by ahmetozalp** [comment]
Merhaba Hakan bu sorunu databaseden skonseptdanismanlik.com kısmını kendi adresinle degştirmeyi denermisin?

**Comment by hakantopuzoglu** [comment]
Evet veritabanında iwt_settings tablosunda site adını değiştirdim. Ancak yine de skonseptdanismanlik.com adresine yönleniyor. Göremediğim başka bir yer var mı acaba?

**Comment by ahmetozalp** [comment]
Son olarak cache dosyasını silmeyi denermisin?

**Comment by hakantopuzoglu** [comment]
cache klasörünü de sildim ama hata çözülmedi. 
http://kurumsal.webteyim.org

Siz deneyebilir misiniz adrese girmeyi?

**Comment by ahmetozalp** [comment]
1- htaccess içini kontrol edin
2- config.php içine tekrar bakın.

Sorununuz büyük ihtimal .htaccess içini düzeltmediginiz için.
