### ISSUE TITLE
Php sürüm?

### ISSUE THREAD

**Issue by halper03** [ahmetozalp/kurumsal-danismanlik-php#4]
Php 5.3 üstünü çalışmıyor sanırım.
gerekli ayarlar yapıltıktan sonra alınan hata.

http://bezmamasepeti.com/

**Comment by ahmetozalp** [comment]
php.ini dosyasından "short_open_tag=On" satırının başındaki # yi kaldırıp tekrar makineyi yeniden başlatın.
